apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: demo-app
    count: 2
