apiVersion: v1
kind: Service
metadata:
  name: my-website-svc
spec:
  type: NodePort 
  selector:
    app: my-website
  ports:
  - protocol: TCP
    port: 80
    # BƯỚC 4: Sửa cổng đích (targetPort)
    targetPort: 8080
