apiVersion: v1
kind: Service
metadata:
  name: my-website-svc
spec:
  # Dòng bạn cần thêm vào:
  type: NodePort 
  # ---------------------
  selector:
    app: my-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
