apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
      - name: web
        # Dòng quan trọng: Trỏ đến image trên Docker Hub của bạn
        # Bot sẽ tự động thay đổi ":latest" thành mã SHA (ví dụ: :a1b2c3d)
        image: johnnyp013/my-first-gitops:latest
        
        # Cổng 8080 (mà file index.js và Dockerfile của bạn đang dùng)
        ports:
        - containerPort: 8080
        
        # Vẫn giữ nguyên phần "tiêm" ConfigMap
        envFrom:
        - configMapRef:
            name: my-website-config
