apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app-prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: demo-app
    count: 5
