apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo-app-prod
  labels:
    app: demo-app
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
