apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-website
  namespace: argocd
  labels:
    app: my-website
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/datpham-qualgo/my-first-gitops.git
    targetRevision: main
    path: k8s
    # Don't use Kustomize, apply YAML files directly
    directory:
      recurse: true
      exclude: "kustomization.yaml"
    
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10