apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/datpham-qualgo/my-first-gitops.git
    targetRevision: main
    path: infrastructure/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app-prod
  syncPolicy:
    # Manual sync for production - requires approval
    syncOptions:
      - CreateNamespace=true
