apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: demo-app
    count: 3
