apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo-app-dev
  labels:
    app: demo-app
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
