name: Build, Push, and Update Manifest

on:
  push:
    branches:
      - main # Chỉ chạy khi push lên nhánh main

# Cấp quyền "write" để Action có thể commit vào chính repo này
permissions:
  contents: write

env:
  # Tên image trên Docker Hub (chúng ta dùng tên repo luôn)
  IMAGE_NAME: johnnyp013/my-first-gitops
  
  # Tên file deployment
  MANIFEST_PATH: deployment.yaml

jobs:
  build-push-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        # Checkout repo hiện tại
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (image tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          # Dùng mã Git SHA ngắn làm tag, ví dụ: a1b2c3d
          tags: type=sha,prefix=,suffix=,format=short 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Đẩy image với tag là mã SHA (ví dụ: johnnyp013/my-first-gitops:a1b2c3d)
          tags: ${{ steps.meta.outputs.version }}

      - name: Cập nhật image tag trong file YAML
        run: |
          # Lấy tag từ bước meta (ví dụ: a1b2c3d)
          NEW_TAG="${{ steps.meta.outputs.version }}"
          echo "Image tag mới là $NEW_TAG"
          
          # Dùng sed để tìm dòng `image:` và thay thế tag
          sed -i "s|${{ env.IMAGE_NAME }}:.*|${{ env.IMAGE_NAME }}:${NEW_TAG}|g" ${{ env.MANIFEST_PATH }}

      - name: Commit và Push thay đổi (nếu có)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          git add ${{ env.MANIFEST_PATH }}
          # Chỉ commit nếu file deployment.yaml thực sự thay đổi
          if ! git diff --staged --quiet; then
            git commit -m "Cập nhật image tag thành ${{ steps.meta.outputs.version }}"
            git push
          else
            echo "Không có thay đổi."
          fi
